---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name : Change index
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name : Copy the config file
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx