- name: Download Influxdb Exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_linux_amd64
    dest: /usr/local/bin
    mode: 0755

- name: Create a service for influxdb exporter
  template:
    src: prometheus-influxdb-stats-exporter.service
    dest: /etc/systemd/system/prometheus-influxdb-stats-exporter.service
  notify:
    - Restart exporter
    - Reload Daemon

- name: Start the service
  service:
    name: prometheus-influxdb-stats-exporter
    state: started
