---
- name: Install Haproxy
  apt:
    name: haproxy

- name: Configure Haproxy 
  template:
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg.j2
  notify: Restart haproxy 

- name: Install HAProxy exporter
  apt:
    name: prometheus-haproxy-exporter
    state: latest

- name: Haproxy exporter config
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart haproxy exporter

- name: Start Haproxy and Exporters
  service: 
    name: "{{ item }}"
    state: started    
  loop: 
    - haproxy
    - prometheus-haproxy-exporter

