- name: Restart exporter
  service:
    name: prometheus-influxdb-stats-exporter
    state: restarted
    enabled: yes

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus-influxdb-stats-exporter.service