- name: Install Grafana 
  apt: 
    deb: https://dl.grafana.com/oss/release/grafana_8.2.3_amd64.deb
    force_apt_get: yes

- name: Start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Reconfigure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana