- name: Install uWSGI packages
  apt: 
    name: 
      - uwsgi
      - uwsgi-plugin-python3

- name: Start uWSGI
  service: 
    name: uwsgi
    state: started

- name: Copy ini file
  template:
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  become: yes
  notify: Restart Uwsgi