- name: Add the user 'agama'
  user:
    name: agama
    comment: web app user
    system: yes

- name: Create install directory
  file:
    state: directory
    path: /opt/agama
    owner: agama
    group: agama
    mode: 0755