{
 "title": "HAProxy",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(keepalived_vrrp_state, \"serverName\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{serverName}}"
    }
   ]
  },
  {
   "title": "HAProxy Server Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up",
     "legendFormat": "{{instance}} {{backend}} {{server}}"
    }
   ]
  },
  {
   "title": "HA Proxy Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(haproxy_up, \"serverName\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{serverName}}"
    }
   ]
  }
 ]
}