
- name: Create Agama directory
  file:
    path: /opt/agama
    state: directory

- name: Download agama install file to /opt/agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama/Dockerfile
    mode: 0755

- name: Log into DockerHub
  docker_login:
    username: "{{docker_user}}"
    password: "{{docker_password}}"
    email: "{{docker_email}}"
  no_log: True

- name: Build the image
  community.docker.docker_image:
    build:
      path: /opt/agama
    name: agama
    source: build

- name: Start agama container
  community.docker.docker_container:
    container_default_behavior: no_defaults
    name: "agama{{item}}"
    image: "agama"
    env:
      "AGAMA_DATABASE_URI=mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    published_ports: "{{ agama_port + item | int }}:8000"
    restart_policy: always
  loop:
    - 1
    - 2
  no_log: true
