- name: Create a backup for resolv conf on remote
  copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.backup
    remote_src: yes

- name : Change resolv file 
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf    
