---
- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: Configure MySQL exporter
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Restart MySQL exporter
  service:
    name: prometheus-mysqld-exporter
    state: restarted
    enabled: yes
