---
- name: Install MySQL exporter
  apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: Configure MySQL exporter
  template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter

- name: Configure MySQL exporter
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf

- name: Create MySQL exporter user
  mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: collect facts about system services
  service_facts:

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  changed_when: ansible_facts.services['prometheus-mysqld-exporter'].state == "stopped"
  notify: Restart MySQL exporter
