- name: Restart keepalived
  service:
    name: keepalived
    state: restarted

- name : Restart exporter
  service:
    name: keepalived-prometheus-exporter.service
    state: restarted

- name: Reload Daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: keepalived-prometheus-exporter.service