---
- name: Install MySql and PyMySql
  apt:
    name: 
      - mysql-server
      - python3-pymysql
  
- name : Copy the config file
  template:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart Mysql

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: yes

- name: MySQL replication user
  community.mysql.mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    host: "%"
    priv: '*.*:REPLICATION SLAVE'
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify: Restart Mysql
  no_log: yes


- name: Turn on dynamic config change
  community.mysql.mysql_variables:
    variable: read_only
    value: 'ON'
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: "hostvars[inventory_hostname]['ansible_default_ipv4']['address'] != mysql_host"
  notify:
  - Reset MySQL source
  - Reset MySQL replica

- name: Keep static as it is
  community.mysql.mysql_variables:
    variable: read_only
    value: 'OFF'
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: "hostvars[inventory_hostname]['ansible_default_ipv4']['address'] == mysql_host"
  notify:
  - Reset MySQL source
  - Reset MySQL replica
