---
- name: Install Prometheus node exporters
  apt:
    name: prometheus-node-exporter
    state: latest

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Enable and start node exporters
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes
