- name: Install Fping
  apt:
    name: fping
    state: latest

- name: Add the user "pinger"
  user:
    name: pinger
    home: /etc/pinger
    shell: /bin/bash
  notify: Restart pinger

- name: Put the config file in place
  template:
    src: pinger.conf
    dest: /etc/pinger/pinger.conf
  notify: Restart pinger

- name: Place the .sh file where it needs to be
  template:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: '0777'
  notify: Restart pinger

- name: Create a service called pinger
  template:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
  notify:
    - Reload Daemon
    - Restart pinger

- name: Execute handlers preemptively
  meta: flush_handlers

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Start pinger
  service:
    name: pinger
    state: started
    enabled: yes
