- name: Restart Influxdb
  service:
    name: influxdb
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: Restart Telegraf
  service:
    name: telegraf
    state: restarted
    enabled: yes
