---
- name: Install Keepalived
  apt:
    name: keepalived
    state: latest

- name: Add the user keepaliver
  user:
    name: keepaliver
    home: /home/keepaliver
    shell: /bin/bash

- name: Configure Keepalived 
  template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.conf.j2

- name: Add the script
  template:
    src: keepalive_script.sh
    dest: /home/keepaliver/keepalived_script
    owner: keepaliver
    mode: '0777'
  notify: Restart keepalived

- name: Download and unarchive keepalived exporter
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.2.0/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create keepalived exporter service
  template:
    src: keepalived-prometheus-exporter.service
    dest: /etc/systemd/system/keepalived-prometheus-exporter.service
  notify: 
    - Reload Daemon
    - Restart exporter
    - Restart keepalived

- name: Start Keepalived and Exporter
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes  
  loop: 
    - keepalived
    - keepalived-prometheus-exporter