---
- name: Install Prometheus
  apt:
    name:
      - prometheus

- name: Change /etc/default/prometheus
  template: 
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart Prometheus
  
- name: Configure Prometheus Job
  template:
    src: prometheus.conf.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart Prometheus
