---
- name: Download Nginx exporter
  apt:
    name: prometheus-nginx-exporter
    state: latest


- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Restart Nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted
    enabled: yes
