---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  notify: Restart Nginx

- name : Copy the config file
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx