
- name: Configure Ip Tables
  template:
    src: iptables
    dest: /var/local/iptables.mangle

- name: Apply iptables rules
  community.general.iptables_state:
    path: /var/local/iptables.mangle
    state: restored
    table: mangle 

- name: Install iptables
  apt:
    name: 
      - iptables-persistent
    state: latest

- template:
    src: iptables
    dest: /etc/iptables/rules.v4

- name: Install Docker 
  apt: 
    name: 
      - docker.io
      - python3-docker
    state: latest

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes