- name: Install Docker 
  apt: 
    name: 
      - docker.io
      - python3-docker
      - iptables-persistent

- name: Configure Ip Tables
  template:
    src: iptables
    dest: /etc/iptables/rules.v4

- name: Apply iptables rules
  community.general.iptables_state:
    path: /etc/iptables/rules.v4
    state: restored
    table: mangle 
  async: "{{ ansible_timeout }}"
  poll: 0


- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes